name: 'Github Rubocop Action'
description: 'Runs rubocop on your PRs :)'
author: 'Justin Roberson, Luiz Fonseca, Alberto Gimeno '
branding:
  icon: 'alert-triangle'
  color: 'red'
runs:
  using: 'docker'
  image: 'Dockerfile'
